//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.ScrumStatus {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.ScrumStatus.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new scrum.
        /// </summary>
        public static string AddNewScrumButtonText {
            get {
                return ResourceManager.GetString("AddNewScrumButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string AddToChannelTitle {
            get {
                return ResourceManager.GetString("AddToChannelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot failure.
        /// </summary>
        public static string BotFailureTitle {
            get {
                return ResourceManager.GetString("BotFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select channel.
        /// </summary>
        public static string ChannelNameValidationText {
            get {
                return ResourceManager.GetString("ChannelNameValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A scrum has already been set up for this team and channel.
        /// </summary>
        public static string DuplicateScrumValidationText {
            get {
                return ResourceManager.GetString("DuplicateScrumValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End scrum.
        /// </summary>
        public static string EndScrumButtonText {
            get {
                return ResourceManager.GetString("EndScrumButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong and I can’t do that right now. Try again in a few minutes..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scrum members present in this scrum..
        /// </summary>
        public static string ErrorNoScrumMembersPresent {
            get {
                return ResourceManager.GetString("ErrorNoScrumMembersPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong saving this info. Try again in a few minutes..
        /// </summary>
        public static string ErrorSavingScrumData {
            get {
                return ResourceManager.GetString("ErrorSavingScrumData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, this scrum has been deleted or inactive..
        /// </summary>
        public static string ErrorScrumConfigurationDetailsNullOrInactive {
            get {
                return ResourceManager.GetString("ErrorScrumConfigurationDetailsNullOrInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} scrum has been deleted..
        /// </summary>
        public static string ErrorScrumDeleted {
            get {
                return ResourceManager.GetString("ErrorScrumDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, this scrum has been deleted..
        /// </summary>
        public static string ErrorScrumDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorScrumDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, only members of this scrum can do this. Ask a colleague to add you..
        /// </summary>
        public static string ErrorUserIsNotPartOfRunningScrumAndTryToEndScrum {
            get {
                return ResourceManager.GetString("ErrorUserIsNotPartOfRunningScrumAndTryToEndScrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, only members of this scrum can do this. Ask a colleague to add you..
        /// </summary>
        public static string ErrorUserIsNotPartOfRunningScrumAndTryUpdateStatus {
            get {
                return ResourceManager.GetString("ErrorUserIsNotPartOfRunningScrumAndTryUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralChannel {
            get {
                return ResourceManager.GetString("GeneralChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to help you! Select or type one of these commands:.
        /// </summary>
        public static string HelpCardTitleText {
            get {
                return ResourceManager.GetString("HelpCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum members.
        /// </summary>
        public static string MembersListTitle {
            get {
                return ResourceManager.GetString("MembersListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find any matches..
        /// </summary>
        public static string NoMatchesFoundText {
            get {
                return ResourceManager.GetString("NoMatchesFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any blockers?.
        /// </summary>
        public static string ScrumDetailsAnyBlockersTitle {
            get {
                return ResourceManager.GetString("ScrumDetailsAnyBlockersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum details.
        /// </summary>
        public static string ScrumDetailsButtonText {
            get {
                return ResourceManager.GetString("ScrumDetailsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: {0} / {1} completed.
        /// </summary>
        public static string ScrumDetailsRespondedVsTotalUserStatus {
            get {
                return ResourceManager.GetString("ScrumDetailsRespondedVsTotalUserStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum details.
        /// </summary>
        public static string ScrumDetailsTitle {
            get {
                return ResourceManager.GetString("ScrumDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What will you do today?.
        /// </summary>
        public static string ScrumDetailsTodayTaskDescriptionTitle {
            get {
                return ResourceManager.GetString("ScrumDetailsTodayTaskDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Blocked!).
        /// </summary>
        public static string ScrumDetailsUserIsBlocked {
            get {
                return ResourceManager.GetString("ScrumDetailsUserIsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What did you do yesterday?.
        /// </summary>
        public static string ScrumDetailsYesterdayTaskDescriptionTitle {
            get {
                return ResourceManager.GetString("ScrumDetailsYesterdayTaskDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string ScrumEnableButtonTitle {
            get {
                return ResourceManager.GetString("ScrumEnableButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ScrumRunningStatusActive {
            get {
                return ResourceManager.GetString("ScrumRunningStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string ScrumRunningStatusClosed {
            get {
                return ResourceManager.GetString("ScrumRunningStatusClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string ScrumStatusCompletedForUser {
            get {
                return ResourceManager.GetString("ScrumStatusCompletedForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started.
        /// </summary>
        public static string ScrumStatusNotStarted {
            get {
                return ResourceManager.GetString("ScrumStatusNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select channel.
        /// </summary>
        public static string SelectChannelPlaceholder {
            get {
                return ResourceManager.GetString("SelectChannelPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select time.
        /// </summary>
        public static string SelectTimePlaceholder {
            get {
                return ResourceManager.GetString("SelectTimePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select time zone.
        /// </summary>
        public static string SelectTimeZonePlaceholder {
            get {
                return ResourceManager.GetString("SelectTimeZonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select User.
        /// </summary>
        public static string SelectUserPlaceholder {
            get {
                return ResourceManager.GetString("SelectUserPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsButtonText {
            get {
                return ResourceManager.GetString("SettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Settings to add a new scrum or edit existing ones:.
        /// </summary>
        public static string SettingsCardTitleText {
            get {
                return ResourceManager.GetString("SettingsCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily start time.
        /// </summary>
        public static string StartEveryDayTitle {
            get {
                return ResourceManager.GetString("StartEveryDayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} people have reported being blocked....
        /// </summary>
        public static string StartScrumCardBlockedText {
            get {
                return ResourceManager.GetString("StartScrumCardBlockedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey guys! Can&apos;t wait to hear from you fellows....
        /// </summary>
        public static string StartScrumCardWelcomeText {
            get {
                return ResourceManager.GetString("StartScrumCardWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select daily start time.
        /// </summary>
        public static string StartTimeValidationText {
            get {
                return ResourceManager.GetString("StartTimeValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice work! This scrum is completed..
        /// </summary>
        public static string SuccessMessageAfterEndingScrum {
            get {
                return ResourceManager.GetString("SuccessMessageAfterEndingScrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command for task module fetch activity. Command is: {0}.
        /// </summary>
        public static string TaskModuleInvalidCommandText {
            get {
                return ResourceManager.GetString("TaskModuleInvalidCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add two or more team members.
        /// </summary>
        public static string TeamMembersValidationText {
            get {
                return ResourceManager.GetString("TeamMembersValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name.
        /// </summary>
        public static string TeamNameTitle {
            get {
                return ResourceManager.GetString("TeamNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name can&apos;t be empty.
        /// </summary>
        public static string TeamNameValidationText {
            get {
                return ResourceManager.GetString("TeamNameValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time zone.
        /// </summary>
        public static string TimeZoneTitle {
            get {
                return ResourceManager.GetString("TimeZoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a time zone.
        /// </summary>
        public static string TimeZoneValidationText {
            get {
                return ResourceManager.GetString("TimeZoneValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter info (300 characters max).
        /// </summary>
        public static string UpdateStatusAnyBlockersPlaceholder {
            get {
                return ResourceManager.GetString("UpdateStatusAnyBlockersPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any blockers?.
        /// </summary>
        public static string UpdateStatusAnyBlockersTitle {
            get {
                return ResourceManager.GetString("UpdateStatusAnyBlockersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update status.
        /// </summary>
        public static string UpdateStatusButtonText {
            get {
                return ResourceManager.GetString("UpdateStatusButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string UpdateStatusSubmitButtonText {
            get {
                return ResourceManager.GetString("UpdateStatusSubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update status.
        /// </summary>
        public static string UpdateStatusTitle {
            get {
                return ResourceManager.GetString("UpdateStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field can&apos;t be empty.
        /// </summary>
        public static string UpdateStatusTodayDescriptionErrorMessage {
            get {
                return ResourceManager.GetString("UpdateStatusTodayDescriptionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter info (300 characters max).
        /// </summary>
        public static string UpdateStatusTodayDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("UpdateStatusTodayDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *What will you do today?.
        /// </summary>
        public static string UpdateStatusTodayDescriptionTitle {
            get {
                return ResourceManager.GetString("UpdateStatusTodayDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field can&apos;t be empty.
        /// </summary>
        public static string UpdateStatusYesterdayDescriptionErrorMessage {
            get {
                return ResourceManager.GetString("UpdateStatusYesterdayDescriptionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter info (300 characters max).
        /// </summary>
        public static string UpdateStatusYesterdayDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("UpdateStatusYesterdayDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *What did you do yesterday?.
        /// </summary>
        public static string UpdateStatusYesterdayDescriptionTitle {
            get {
                return ResourceManager.GetString("UpdateStatusYesterdayDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you’re done, select End scrum at the bottom of the form. Once you end a scrum, no one can make any more updates to that scrum. Just start a new scrum when you’re ready to get status updates again..
        /// </summary>
        public static string WelcomeCardEndScrumTextDesc {
            get {
                return ResourceManager.GetString("WelcomeCardEndScrumTextDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **End scrum**.
        /// </summary>
        public static string WelcomeCardEndScrumTextHeading {
            get {
                return ResourceManager.GetString("WelcomeCardEndScrumTextHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string WelcomeCardSettingsButtonText {
            get {
                return ResourceManager.GetString("WelcomeCardSettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you ask me to start a scrum, I’ll create a form where people can enter their current status. Everyone can look at these updates..
        /// </summary>
        public static string WelcomeCardStartScrumTextDesc {
            get {
                return ResourceManager.GetString("WelcomeCardStartScrumTextDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Start scrum**.
        /// </summary>
        public static string WelcomeCardStartScrumTextHeading {
            get {
                return ResourceManager.GetString("WelcomeCardStartScrumTextHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I help you get status updates from your team. Everyone in the channel can participate..
        /// </summary>
        public static string WelcomeCardSubtitleText {
            get {
                return ResourceManager.GetString("WelcomeCardSubtitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string WelcomeCardTitle {
            get {
                return ResourceManager.GetString("WelcomeCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to start a scrum now?.
        /// </summary>
        public static string WelcomeCardWantToStartScrumText {
            get {
                return ResourceManager.GetString("WelcomeCardWantToStartScrumText", resourceCulture);
            }
        }
    }
}
